name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: kaitaoms/comic-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Web App with Docker support
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az appservice plan create --name myAppServicePlan --resource-group comic --sku B1 --is-linux
          az webapp create --resource-group comic --plan myAppServicePlan --name comic-web-app --deployment-container-image-name kaitaoms/comic-service:latest
        
    - name: Configure docker image
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config container set --name comic-web-app --resource-group comic --docker-custom-image-name kaitaoms/comic-service:latest --docker-registry-server-url https://registry.hub.docker.com
